# Generated by Django 3.0.8 on 2020-07-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TestUser',
        ),
        migrations.AlterModelTable(
            name='testuser',
            table='testusers',
        ),
    ]
