# Generated by Django 3.0.8 on 2020-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200702_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=128, verbose_name='사용자이메일'),
        ),
    ]
