# Generated by Django 3.0.8 on 2020-07-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_testuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일자')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TestUser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'db_table': 'board',
            },
        ),
    ]
