# Generated by Django 3.0.8 on 2020-07-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('name', models.CharField(max_length=64, verbose_name='태그명')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AlterField(
            model_name='board',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일자'),
        ),
        migrations.AlterModelTable(
            name='board',
            table='boards',
        ),
        migrations.AddField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(related_name='boards', to='board.Tag', verbose_name='태그'),
        ),
    ]
